version: '3.8'
services:
  db:
    image: mysql/mysql-server:latest
    container_name: my-mysql
    restart: always
    environment:
      - MYSQL_USER=admin
      - MYSQL_DATABASE=mysqlDB
      - MYSQL_PASSWORD=mysqlPW
      - MYSQL_ROOT_PASSWORD=mysqlPW
    ports:
      - '3306:3306'
    volumes:
      - mysql-volume:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql #
    network_mode: 'host'
volumes:
  mysql-volume:
    driver: local
